version: "3.9"

services:
  sofkabankapp:
    env_file:
      - app.env
    build: .                                                                        
    image: sofkabankapp:1.0
    container_name: sofkabankapp
    ports:
      - ${D_PORTAPP_C}:${D_PORTAPP_L}
    depends_on:
      - mongodb
      - rabbitmq  
  
  mongodb:
    image: mongo:latest
    container_name: sofkabankmongo           
    ports:
      - ${D_PORTDB_C}:${D_PORTDB_L}
    volumes:
      - ./data:/data/db

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: sofkabankrabbit
    environment:
      - RABBITMQ_DEFAULT_USER=${D_RABBITUSER}
      - RABBITMQ_DEFAULT_PASS=${D_RABBITPASS}
    ports:
      - ${D_RABBITPORTS_C}:${D_RABBITPORTS_L}
      - ${D_RABBITPORTS_PORTAL_C}:${D_RABBITPORTS_PORTAL_L}
              