spring:
   data:
      mongodb:
         host: localhost
         port: 27017
         database: sofka
         username: ${USERMONGO}
         password: ${PASSMONGO}
         authentication-database: admin 

logging:
  level:
     org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
     