# Generated by Django 5.1 on 2024-08-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_initial', '0002_registry_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
