# Generated by Django 5.1 on 2024-08-15 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_initial', '0003_registry_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paydate', models.DateField()),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_initial.registry')),
            ],
        ),
    ]
