# Generated by Django 5.1 on 2024-08-15 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_initial', '0005_paymentmethod_pay_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('blod', models.CharField(max_length=3)),
                ('observation', models.TextField(null=True)),
                ('registry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app_initial.registry')),
            ],
        ),
    ]
