# Generated by Django 5.1 on 2024-08-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foreign_exchange', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('items', models.TextField(max_length=200)),
            ],
        ),
    ]
