# Generated by Django 5.1 on 2024-08-20 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('local_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foreign_exchange', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.item')),
            ],
        ),
    ]
