spring:
   data:
      mongodb:
         host: localhost
         port: 27017
         database: sofkaBank
         username: ${USERMONGO}
         password: ${PASSMONGO}
         authentication-database: admin 

commission:
   atm:
      amount: 2 

logging:
   level:
     org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG 