AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  send-bot-app

  Sample SAM Template for send-bot-app

Globals:
  Function:
    MemorySize: 512  
    Timeout: 10
    Runtime: java21
    Architectures:
    - x86_64
    LoggingConfig:
      LogFormat: Text

Parameters:
  environment:
    Type: String
  country:
    Type: String
  ParentStackName:
    Type: String    

Resources:
# --------- SQSs --------- #
  sendQueueDlq:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${ParentStackName}-sqs-sendqueuedlq

  sendQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt sendQueueDlq.Arn
        maxReceiveCount: 5
      QueueName: !Sub ${ParentStackName}-sqs-sendqueue

# --------- lambda --------- #
  sendFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ParentStackName}-lbda-sendfunction
      Role: !GetAtt sendLambdaRole.Arn
      CodeUri: ../../source/mssendsoap
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Environment:
        Variables:
          ENV_APP: !Ref environment
          COUNTRY: !Ref country
      Events:
        sendEventSQS:
          Type: SQS
          Properties:
            Queue: !GetAtt sendQueue.Arn
            BatchSize: 1
            Enabled: true
    Metadata:
      BuildMethod: makefile

  # --------- API --------- #
  sendAPIRest:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub ${ParentStackName}-apigateway-sendapirest
      EndpointConfiguration: 
        Types: 
        - REGIONAL

  v1sendAPIRest:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref sendAPIRest
      ParentId: !GetAtt sendAPIRest.RootResourceId
      PathPart: v1

  sendResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref sendAPIRest
      ParentId: !Ref v1sendAPIRest
      PathPart: sendsend
    Metadata:
      SamResourceId: sendsend

  sendMethodSQS:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref sendAPIRest
      ResourceId: !Ref sendResource
      HttpMethod: POST
      Integration:
        IntegrationResponses:
          - StatusCode: 200
        IntegrationHttpMethod: POST
        RequestTemplates:
          application/json: "Action=SendMessage&MessageBody=$util.urlEncode($input.body)"
        RequestParameters:
          integration.request.header.Content-Type: "'application/x-www-form-urlencoded'" 
        Type: AWS
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:sqs:path//${queueName}
          - queueName: !GetAtt sendQueue.QueueName
        Credentials: !GetAtt sendApiRoleSqs.Arn
      MethodResponses:
        - StatusCode: 200
      AuthorizationType: NONE

  sendAPIRestDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: sendMethodSQS
    Properties:
      RestApiId: !Ref sendAPIRest

  sendAPIRestStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref sendAPIRestDeployment
      RestApiId: !Ref sendAPIRest
      StageName: !Ref environment

  sendApiRoleSqs:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${ParentStackName}-sendApiRoleSqs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "sqs:SendMessage"
                Resource: !GetAtt sendQueue.Arn


  sendLambdaRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: !Sub ${ParentStackName}-sendlambdarole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
            - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole
      Policies:
        - PolicyName: !Sub ${ParentStackName}-sendlambdapolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:             
                  - secretsmanager:GetSecretValue               
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub  "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:ate/${environment}/*"

  sendSqsInputPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "apigateway.amazonaws.com"
            Resource: !GetAtt sendQueue.Arn
            Action:
              - "sqs:SendMessage"
              - "sqs:ReceiveMessage"
            Condition:
              ArnEquals:
                aws:SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${sendAPIRest}/*"
      Queues:
        - !Ref sendQueue
          

Outputs:
  sendApi:
    Description: "API Gateway endpoint URL for Prod stage for send function"
    Value: !Sub "https://${sendAPIRest}.execute-api.${AWS::Region}.amazonaws.com/${environment}/v1/sendsend"