version = 0.1

[default.build.parameters]
cached = true
parallel = true

# ------------------------------ DESARROLLO-VE ------------------------------ #
[dev.build.parameters]
cached = true
parallel = true

[dev.deploy.parameters]
stack_name = "dev-pos-integration-ve"
s3_prefix = "dev-pos-integration-ve"
resolve_s3 = true
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "environment=\"dev\" country=\"ve\""

[dev.delete.parameters]
stack_name = "dev-pos-integration-ve"
s3_prefix = "dev-pos-integration-ve"
region = "us-west-2"
# ------------------------------------------------------------ #

