AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Stack principal de integraciones telegram stellar


# ------------------ Parámetros de la aplicación ------------------ #

Parameters:
  environment:
    Type: String
    Default: dev  
    Description: 'Ambientes de implementacion: dev, qa, prod.'
    AllowedValues:
      - dev
      - qa
      - prod

  country:
    Type: String
    Description: 'Paises de implementacion: cr, gt, sv, ve.'
    Default: ve
    AllowedValues:
      - gt
      - sv
      - ve

Resources:
 # --------- STACKS ------------------- #
 # --------- telegram bot app --------- #        
  clientoutputstack: 
    Type: AWS::Serverless::Application
    Properties:
      Location: ./telegram_bot_spring/template.yaml