AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  telegram-bot-app

  Sample SAM Template for telegram-bot-app

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    LoggingConfig:
      LogFormat: JSON

Resources:
  TelegramFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: telegram_bot_spring/
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Runtime: java21
      Architectures:
      - x86_64
      MemorySize: 512
    Metadata:
      BuildMethod: makefile
