server.port=${D_PORTAPP_L}

EPA.Deposito.Sucursal=${D_SUCURSAL}
EPA.Deposito.Cajero=${D_DEPOSITO}
EPA.Deposito.OtraCuenta=${D_CUENTA}

EPA.Compra.Fisica=${D_FISICA}
EPA.Compra.Web=${D_WEB}

#------------------------------------------------------------------ (RABBIT)

app.rabbit.URL=${D_RABBITURL}

#------------------------------------------------------------------ (MONGO)

spring.data.mongodb.host=${D_HOSTDB}
spring.data.mongodb.port=${D_PORTDB_L}
spring.data.mongodb.database=${D_DBMONGO}
spring.data.mongodb.username=${D_USERMONGO}
spring.data.mongodb.password=${D_PASSMONGO}
spring.data.mongodb.authentication-database=${D_AUTHPASSMONGO}





