server.port=8080

EPA.Deposito.Sucursal=${SUCURSAL}
EPA.Deposito.Cajero=${DEPOSITO}
EPA.Deposito.OtraCuenta=${CUENTA}

EPA.Compra.Fisica=${FISICA}
EPA.Compra.Web=${WEB}

#------------------------------------------------------------------ (MONGO)
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=DB_BANKING
spring.data.mongodb.username=${USERMONGO}
spring.data.mongodb.password=${PASSMONGO}
spring.data.mongodb.authentication-database=admin

