server.port=${PORTAPP}

EPA.Deposito.Sucursal=${SUCURSAL}
EPA.Deposito.Cajero=${DEPOSITO}
EPA.Deposito.OtraCuenta=${CUENTA}

EPA.Compra.Fisica=${FISICA}
EPA.Compra.Web=${WEB}

#------------------------------------------------------------------ (RABBIT)

app.rabbit.URL=${RABBITURL}

#------------------------------------------------------------------ (MONGO)

spring.data.mongodb.host=${HOSTDB}
spring.data.mongodb.port=${PORTDB}
spring.data.mongodb.database=${DBMONGO}
spring.data.mongodb.username=${USERMONGO}
spring.data.mongodb.password=${PASSMONGO}
spring.data.mongodb.authentication-database=admin





