spring:
   data:
      mongodb:
         host: localhost
         port: 27017
         database: sofkaBank
         username: ${USERMONGO}
         password: ${PASSMONGO}
         authentication-database: admin 
   datasource:
      driver-class: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sofkabank
      username: ${USERMYSQL}
      password: ${PASSMYSQL}
   jpa:
      show-sql: true

commission:
   atm:
      amount: 2 

logging:
   level:
     org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG 